language: python

addons:
  apt:
    packages:
      - libhdf5-serial-dev
      - netcdf-bin
      - libnetcdf-dev

env:
  global:
    #- DEPENDS="cython>=0.19"
    - NO_NET=1

matrix:
  include:
    - python: 2.7

  allow_failures:
    - python: "3.6-dev"
    - python: "nightly"

# start Virtual X, so default matplotlib backend works
before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

# command to install dependencies
install:
    - if [[ $TRAVIS_PYTHON_VERSION == 3.3 ]];
      then pip install -r requirements33.travis.txt;
      else pip install -r requirements.travis.txt;
      fi
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform


# command to run tests
script: 
    - export PYTHONPATH=$PYTHONPATH:.
    - nosetests -v -w ./autotest --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_flopy_bbe42a22c2_0
  - python -m properform Push 47.88.50.110:15554 asdf_flopy_bbe42a22c2_0 ./profile_flopy_bbe42a22c2_0

 #2017-08-12 17:13:00 modified at 0